# Run this to validate this file:
# curl --data-binary @codecov.yml https://codecov.io/validate
codecov:

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: auto
        if_not_found: success  # no commit found? still set a success

    patch: no
    changes: no

comment: true
