version: 2
jobs:
  tests:
    docker:
      - image: python:3.6-stretch
        environment:
          ENVIRONMENT: dev
          DEBUG: true
          POSTGRES_HOST: localhost
          POSTGRES_DB: starter
          POSTGRES_PASSWORD: "1234567890"
          REDIS_HOST: localhost
          SECRET_KEY: "88t7GMYBwWW2FS27"
      - image: postgres:10.4
        environment:
          POSTGRES_USER: 'start'
          POSTGRES_PASSWORD: '1234567890'
          POSTGRES_DB: 'starter'
      - image: redis:4.0.10
    working_directory: /var/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true
      - run:
          name: Install dependencies
          command: |
            apt-get update && \
            apt-get install -y bash musl-dev libc-dev gcc git && \
            pip3 install -U pip && \
            pip3 install -r requirements.txt && pip3 install -r requirements-dev.txt
      - run:
          name: Wait for dbs
          command: |
            ./bin/wait-for -t 60 --host=localhost --port=5432
            ./bin/wait-for -t 60 --host=localhost --port=6379
      - run:
          name: Run unit tests
          command: ./bin/test && codecov
          environment:
            COVERAGE_FILE: all

workflows:
  version: 2
  starter:
    jobs:
      - tests
