version: 2
jobs:
  tests:
    docker:
      - image: starter

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true
      - run:
          name: Wait for dbs
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run unit tests
          command: ./bin/test && codecov --token=$CODECOV_TOKEN
          environment:
            COVERAGE_FILE: all

workflows:
  version: 2
  discovery:
    jobs:
      - tests
